### ISSUE TITLE
[Discussion] New vector icons

### ISSUE THREAD

**Issue by brainscript** [cgeo/cgeo.github.io#105]
I'm currently working on replacing most of the old `.png` icons with new `.svg` vector icons.
I opened this issue as a little **todo list** for me and a place to **discuss about the icons**.
### Todo
- [x] Social media icons (Facebook, Google+ & Twitter)
- [x] Download buttons (Google Play, APK file)
- [ ] c:geo logo
- [ ] send2cgeo logo
- [x] Donate button

**Comment by brainscript** [comment]
![Download buttons](https://cloud.githubusercontent.com/assets/8706734/17407132/77e5c5ac-5a66-11e6-902d-6434a3f6c45a.png)
_My current attempt on making new download buttons._

Any thoughts on them? And should the "F" in "File" be lower case?

**Comment by SammysHP** [comment]
> c:geo logo @SammysHP Do you know who made the original one?

Unknown person. But I already made an svg version of it: https://github.com/cgeo/cgeo/blob/master/main/project/rawimages/c-geo_icon.svg

**Comment by brainscript** [comment]
@SammysHP And what do you think about the download buttons?

**Comment by UniQP** [comment]
Whether it's upper or lower case depends on the style guideline, and I guess we don't have one.
I would prefer upper case (reading the button description as a title).

**Comment by Bananeweizen** [comment]
looks good to me

**Comment by brainscript** [comment]
OK, due to the fact that I'm currently in vacation I will continue my work in this (and merge the download buttons) next week.

**Comment by brainscript** [comment]
**I'm back ...**
### Donate button
... and I finished a (in my opinion) good looking donate button in the style of the social icons.
Maybe the button looks too playful, but I think it fits nicely into the page.

![donatebutton](https://cloud.githubusercontent.com/assets/8706734/17965842/f7d2ffe2-6abe-11e6-88f0-95f0d3121dc2.png)

@SammysHP @Bananeweizen What do you guys think about it?

### Hover mixin
I also created a useful mixin to easily add a simple hover effect to elements:
```
@mixin hover {
  opacity: 0.5;
  &:hover { opacity: 1; }
  transition: opacity 0.2s;
}
```
@SammysHP In my last commit I also added a transition, but you said ...
> However the transition is also applied after page load, so the icons are flashing/fading at the beginning.

The flashing/fading only happens if refresh the page while having the cursor on the object. (Firefox 48.0) That's not really a problem I guess.

>  I removed the transition (we do not use it for other elements anyway).

Now we use it for the donate button as well.

### Okay?
If you're okay with that, I will change that stuff in my fork and create a pull request.

**Comment by Bananeweizen** [comment]
Looks okay to me. I would go without the shaking of the letters (and probably without the ! character), but that is probably just personal taste I can't cite some typographic rules here. :)

**Comment by SammysHP** [comment]
@brainscript Any update for the other graphics?

Maybe you're able to "fix" the font of our SVG icon: https://github.com/cgeo/cgeo/blob/master/main/project/rawimages/c-geo_icon.svg
(Original for reference: https://github.com/cgeo/cgeo/blob/master/main/project/rawimages/c_geo_icon_512.png)

And here's something for the Google banner: https://play.google.com/intl/en_us/badges/

**Comment by Bananeweizen** [comment]
judging by the above screenshot, @brainscript was already using the official current play store badge. :)

**Comment by brainscript** [comment]
@SammysHP @Bananeweizen They are basically finished, I just have to do HTML stuff.

I also made a F-Droid badge for fun. This would either lead to an FAQ explaining how to add the package source or to [the currently not existent package on the F-Droid website](https://f-droid.org/repository/browse/?fdid=cgeo.geocaching). _Is this going to happen some day?_

![bildschirmfoto vom 2016-09-29 21-14-08](https://cloud.githubusercontent.com/assets/8706734/18968540/b5aaa2d2-8689-11e6-943e-732ce89ba7d8.png)

When I get the time I will get this done tomorrow or at the weekend.

**Comment by SammysHP** [comment]
Great idea!

> Is this going to happen some day?

Maybe. But only if they change their mind about our Google and other third party dependencies and API key requirements.

**Comment by kumy** [comment]
We host our own F-Droid repository, maybe it could be linked to http://www.cgeo.org/development.html

**Comment by Bananeweizen** [comment]
Just looked at the f-droid page. I suggest to link the badge directly to the repo at https://fdroid.cgeo.org/. If you open that page, it immediately tells what to do with it. I would rather not point normal (non development) users to the development page just for installing the app, even though f-droid users are probably above average technical knowledge. :)

**Comment by kumy** [comment]
This page is not well polished for our users to be directed to it. The page has not so much information and point to the developers page with a text link. Not a nice user experience.
Shouldn't we build a page with good explanations (urls, fingerprint, qrcode...) branded with our cgeo theme?

On September 30, 2016 8:09:54 PM GMT+02:00, Michael Keppler <notifications@github.com> wrote:
>Just looked at the f-droid page. I suggest to link the badge directly
>to the repo at https://fdroid.cgeo.org/. If you open that page, it
>immediately tells what to do with it. I would rather not point normal
>(non development) users to the development page just for installing the
>app, even though f-droid users are probably above average technical
>knowledge. :)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo.github.io/issues/105#issuecomment-250813518

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Bananeweizen** [comment]
If you want to create a dedicated page for the f-droid installation (and remove the related text from the development page), then go ahead, of course.

**Comment by brainscript** [comment]
I'm closing this here due to the #138 redesign I - from now on @shroudedcode - made.
