### ISSUE TITLE
Huge design overhaul

### ISSUE THREAD

**Issue by shroudedcode** [cgeo/cgeo.github.io#138]
Hey there! I'm @brainscript's new account and I've got some pretty huge news to share. Over the last few works I've been working on something big and I think it's time to present ...

### The huge c:geo website design overhaul (everyone was secretly hoping for)!

After vectorizing some of the icons on the site in #110, I realized that its overall design is just no longer contemporary, so I challenged myself to completely redesign most of it.

Here's how the finished result of the homepage looks like. I removed a lot of the content that was on it originally, but replaced it with something better. A nice set of icons resembling c:geo's features and three actions at the bottom of the page. And then there's the new download buttons that reveals the three different download options after clicking on it (doesn't require JavaScript btw). I also removed the screenshot, because they didn't really fit in after I've redesigned the rest.

![Homepage redesign](https://cloud.githubusercontent.com/assets/29176678/26779756/f62ac42e-49e6-11e7-91b9-e20525739d30.png)

### Other changes

I also made a bunch of non-design changes including ...
- an `.editorconfig` file, learn more about it [here](http://editorconfig.org/) and make sure to use [the respective plugin for your IDE](http://editorconfig.org/#download) when editing the site in the future
- a better indentation of the `faq.yml`
- pretty permalinks (without `.html`)
- [Twitter app metadata](https://dev.twitter.com/cards/mobile)
- lots of new `.yml` data files for actions, download sources, feature icons and navigation items
- CSS vendor imports inside of the `.scss` files
- [Zepto.js](http://zeptojs.com/) instead of [jQuery](https://jquery.com/)

### Tasks I can't do myself
- [ ] Change the domain from `www.cgeo.org` to `cgeo.org` (Is changing the CNAME enough?)
The `www.` is unnecessary and looks unprofessional.
- [ ] Enable HTPPS (Should be somewhere in the GitHub pages options ...)
Simple having that little :lock: next to the address makes a website appear much more legit.

www.cgeo.org | [socket.io](socket.io) (example)
--- | ---
| ![image](https://cloud.githubusercontent.com/assets/29176678/26781499/255035c4-49ef-11e7-9140-6b5e947eb1ef.png) | ![image](https://cloud.githubusercontent.com/assets/29176678/26781483/07a895de-49ef-11e7-9708-7b68ed3baf2b.png)

- [ ] Open-source **all** parts of the website (send2cgeo API, status API, ...)
This would allow me to (for example) redesign the send2cgeo UI.

---

*I hope you like my redesign. :smiley_cat: If you have any questions or ideas, leave them as a comment on this issue or on [the pull request](https://github.com/cgeo/cgeo.github.io/pull/139) (when they are code-related).*

**Comment by SammysHP** [comment]
I haven't checked the code or the actual site yet, but I really like the screenshot! Give me some days to check everything and wait for feedback from others.

> Change the domain from `www.cgeo.org` to `cgeo.org` (Is changing the CNAME enough?)
The `www.` is unnecessary and looks unprofessional.

Not sure, but I think there was a reason to do it this way.

> Enable HTPPS (Should be somewhere in the GitHub pages options ...)
Simple having that little :lock: next to the address makes a website appear much more legit.

Sadly this is not possible because we host our website on GitHub pages and there is no possibility to provide our own certificate.

> Open-source **all** parts of the website (send2cgeo API, status API, ...)
This would allow me to (for example) redesign the send2cgeo UI.

The code of the status page is here: https://github.com/cgeo/cgeo-status
send2cgeo is not open source yet because of security concerns (no review of the code yet).

I'll post some more TODOs once I've tested the code.

**Comment by kumy** [comment]
>> Enable HTPPS (Should be somewhere in the GitHub pages options ...)
Simple having that little :lock: next to the address makes a website appear much more legit.
>
>Sadly this is not possible because we host our website on GitHub pages and there is no possibility to     provide our own certificate.

Yep, this is not native on GitHub for "custom" domains. But it may be possible using reverse proxy in front. There lots of tutorials doing this using Cloudflare.

PS: I love the design :)

**Comment by SammysHP** [comment]
Merged in 4ac293d7756ce9e98772781e2777b59f751a9233.

**Comment by shroudedcode** [comment]
@SammysHP Don't forget to change the domain to `cgeo.org`.

**Comment by SammysHP** [comment]
I'll open another issue for that. ;)

PS: Another issue with redirections will follow.

**Comment by Lineflyer** [comment]
I was not available last days but only now see this nice suggestion and its live already.
I really like the look! Thanks @shroudedcode for this contribution.
