### ISSUE TITLE
New website release plan

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo.github.io#27]
TODO:
- [x] Add development.html #30 
- [x] Add support.html #43 
- [x] Add send2cgeo.html #44 
- [x] Bring send2cgeo server functions to the new website (e.g. iframe) #56
- [x] Add nightly APKs to download.cgeo.org (see [here](http://cgeo.github.io/development.html))
- [x] Change download location on notification system (see [here](https://github.com/cgeo/cgeo-status/issues/3))
- [x] [Add a CNAME file to the repository](https://help.github.com/articles/adding-a-cname-file-to-your-repository/)
- [x] [Add a CNAME entry to the DNS configuration of cgeo.org](https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/)
- Redirect the home page of status.cgeo.org to the embedded status page <-- Moved to a dedicated issue
- [x] Update links to FAQ in c:geo sourcecode https://github.com/cgeo/cgeo/pull/4999
- [x]  Redirect faq.cgeo.org to new website (once live) #57
- [x] Redirect send2.cgeo.org to new website (once live) #68
- [x] Remove warning from main page

**Comment by mucek4** [comment]
I'll crate download subdomains today. Shall downloads be still hosted on my server or shall we move them somewhere else?

**Comment by SammysHP** [comment]
On your server. Shortest path from CI. ;)

**Comment by Lineflyer** [comment]
We need to fix #30, #43 and #44 before going live IMO.
Added above.

**Comment by Lineflyer** [comment]
Added "Update links to FAQ in c:geo sourcecode"

**Comment by SammysHP** [comment]
Another idea for the APKs: The workspaces on jenkins are readable for everyone. What do you think about redirecting from download.cgeo.org/* to the respective files in the workspaces?

**Comment by Bananeweizen** [comment]
I don't like that idea. This violates the single responsibility principle. And it creates restrictions on our build which can easily be violated, e.g. if someone manually wipes the workspaces or renames a project. Also Jenkins is slow, while github is fast. Also the release would not be atomic, users could start downloading the file while it is not yet copied completely on the local filesystem.

**Comment by Lineflyer** [comment]
Send2cgeo.html was added but the server functions need to be implemented (linked, via iframe, etc.).
Adapted the task description above

**Comment by Lineflyer** [comment]
@mucek4 Any progress regarding download.cgeo.org creation and send2.cgeo.org inlcuding?

**Comment by mucek4** [comment]
download is created, I promised link to rsudev.

**Comment by mucek4** [comment]
@rsudev script on server done. I have send you usage to email.

**Comment by Lineflyer** [comment]
AFAICS the nightlies are now also automatically copied to download.cgeo.org. 
So I have set this step as done above.

@mucek4 Correct?

**Comment by SammysHP** [comment]
Plugin nightly are missing.

**Comment by mucek4** [comment]
There is no plugin nightly job.

**Comment by SammysHP** [comment]
But we have plugin nightly here: http://cgeo.org/nightly.html

**Comment by mucek4** [comment]
Nightly calnedar is on cgeo-calendar-nightly.apk
Nightly no-jit is cgeo-nightly-nojit.apk

**Comment by Lineflyer** [comment]
Marked some more things as done.

**Comment by Lineflyer** [comment]
> Redirect the home page of status.cgeo.org to the embedded status page

Not sure about this point in the ToDo...
IMHO the status page can stay where it is. We should only remove the header section refering to the old homepage and leave just the center page.
However as this is only kind of an "internal" page, I do not see this as critical for the release of the webpage. 

Comments?

**Comment by Bananeweizen** [comment]
>> However as this is only kind of an "internal" page, I do not see this as critical for the release of the webpage.

Exactly my opinion. It might be useful to unify the stylesheet and do some other cleanups, but this page is not prominently linked (and should not be).

**Comment by samueltardieu** [comment]
I plan to redirect http://status.cgeo.org/ (just the homepage) to http://www2.cgeo.org/status.html anyway.

**Comment by mucek4** [comment]
so ok. I have to to next things:
Add a CNAME file to the repository
Add a CNAME entry to the DNS configuration of cgeo.org
Redirect faq.cgeo.org to new website (once live) #57
Redirect send2.cgeo.org to new website (once live) #68 

In one single GO. Once I do that webpage goes LIVE. Say when?

**Comment by Lineflyer** [comment]
Anytime now I would say.
Maybe in the evening when some are arouns to see if its working?
Like 05.06., 21:00 ?

**Comment by Lineflyer** [comment]
Announcement:
As just agreed on IRC we will start going live with the new website today at about 8-9pm CEST and sync and test activities via IRC.

If there is any blocking issue for anyone please cry out loud now :)

**Comment by Lineflyer** [comment]
WE ARE LIVE
